# Generated by Django 2.0.3 on 2018-03-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('crop_grown', models.CharField(max_length=200)),
                ('sowing_date', models.DateField(verbose_name='sowing date')),
                ('coordinates_array', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Farmerdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduledata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_after', models.IntegerField(default=0)),
                ('fertiliser', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_unit', models.CharField(max_length=200)),
                ('farm', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fm', to='leancrop.Farmdata')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd', to='leancrop.Farmerdata')),
            ],
        ),
        migrations.AddField(
            model_name='farmdata',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd', to='leancrop.Farmerdata'),
        ),
    ]
